<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
use Interop\Container\ContainerInterface;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'SECRET' => 
  array (
    'defaultValue' => '4JJTUkZSFkVURpzkpevw',
    'type' => 'string',
    'comment' => 'A random string. It should be different for any application deployed.',
  ),
  'DEBUG' => 
  array (
    'defaultValue' => true,
    'type' => 'bool',
    'comment' => 'Set to true to enable debug/development mode.',
  ),
  'DB_HOST' => 
  array (
    'defaultValue' => 'localhost',
    'type' => 'string',
    'comment' => 'The database host (the IP address or URL of the database server).',
  ),
  'DB_PORT' => 
  array (
    'defaultValue' => '',
    'type' => 'int',
    'comment' => 'The database port (the port of the database server, keep empty to use default port).',
  ),
  'DB_NAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The name of your database.',
  ),
  'DB_USERNAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The username to access the database.',
  ),
  'DB_PASSWORD' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The password to access the database.',
  ),
));

$moufManager->setAllVariables(array (
  'splashDefaultControllersNamespace' => 'Arceau\\Controllers\\',
  'splashDefaultViewsDirectory' => 'views/',
  'splashexludeextentions' => 
  array (
    0 => 'js',
    1 => 'ico',
    2 => 'gif',
    3 => 'jpg',
    4 => 'png',
    5 => 'css',
    6 => 'woff',
    7 => 'ttf',
    8 => 'svg',
    9 => 'eot',
  ),
  'splashexludefolders' => 
  array (
    0 => 'vendor',
  ),
  'doctrine_entityManager_generatePatch' => false,
));

$moufManager->addComponentInstances(array (
  '__anonymous__61bc_1625135474' => 
  array (
    'class' => 'Mouf\\Security\\Views\\SimpleLoginView',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_112948783' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\ClearCache\\QueryCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1189883918' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\ConvertDoctrine1SchemaCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1225379122' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\ConvertMappingCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1353209551' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\SchemaTool\\CreateCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1362371042' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\MappingDescribeCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1435874693' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ListPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__ad9b_1483274512' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\SchemaTool\\UpdateCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1494388719' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\SchemaTool\\DropCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1607929313' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\SkipPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__ad9b_1641113894' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\RevertPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__ad9b_1641201104' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ApplyPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__ad9b_1662283823' => 
  array (
    'class' => 'Doctrine\\DBAL\\Driver\\PDOMySql\\Driver',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_1706001315' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\ClearCache\\ResultCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_2021859385' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\ValidateSchemaCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_315051112' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\GenerateRepositoriesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_353335263' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\RunDqlCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_359575562' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\GenerateProxiesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_38224610' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\InfoCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_506899040' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\EnsureProductionSettingsCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_536952336' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\GenerateEntitiesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_793827093' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Command\\ClearCache\\MetadataCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__ad9b_914054494' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ApplyAllPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__ad9b_960329136' => 
  array (
    'class' => 'Doctrine\\Common\\EventManager',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  'annotationReader' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\Common\\Annotations\\CachedReader',
    'external' => false,
    'code' => '// Using composer autoloader
$loader = require ROOT_PATH . \'vendor/autoload.php\';
\\Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader(array($loader, \'loadClass\'));

// Creating a new AnnotationReader
$reader = new \\Doctrine\\Common\\Annotations\\AnnotationReader();
return new \\Doctrine\\Common\\Annotations\\CachedReader($reader, $container->get("defaultDoctrineCache"));',
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fallback' => 'fileCacheService',
    ),
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'messageWidget',
      ),
    ),
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'bodyTemplate' => 
  array (
    'class' => 'Arceau\\Template\\BodyTemplate',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setTitle' => 
      array (
        'value' => 'Arceau - Gestion',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setHeader' => 'headerTemplate',
      'setFooter' => 'footerTemplate',
      'setContent' => 'contentTemplate',
    ),
  ),
  'bootstrapRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.template.bootstrap/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'template',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'bootstrapTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setContent' => 'block.content',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setTemplateRenderer' => 'bootstrapRenderer',
      'setDefaultRenderer' => 'defaultRenderer',
    ),
  ),
  'clientDao' => 
  array (
    'class' => 'Arceau\\Model\\DAOs\\ClientDao',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'entityManager',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'component.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/bootstrap/js/bootstrap.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/bootstrap/css/bootstrap.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'component.jquery' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/jquery/jquery.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'console' => 
  array (
    'class' => 'Mouf\\Console\\ConsoleApplication',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setHelperSet' => 'helperSet',
      'setCommands' => 
      array (
        0 => '__anonymous__ad9b_1435874693',
        1 => '__anonymous__ad9b_914054494',
        2 => '__anonymous__ad9b_1641201104',
        3 => '__anonymous__ad9b_1607929313',
        4 => '__anonymous__ad9b_1641113894',
        5 => 'dbalRunSqlCommand',
        6 => 'dbalImportCommand',
        7 => 'dbalReservedWordsCommand',
        8 => '__anonymous__ad9b_793827093',
        9 => '__anonymous__ad9b_1706001315',
        10 => '__anonymous__ad9b_112948783',
        11 => '__anonymous__ad9b_1353209551',
        12 => '__anonymous__ad9b_1483274512',
        13 => '__anonymous__ad9b_1494388719',
        14 => '__anonymous__ad9b_506899040',
        15 => '__anonymous__ad9b_1189883918',
        16 => '__anonymous__ad9b_315051112',
        17 => '__anonymous__ad9b_536952336',
        18 => '__anonymous__ad9b_359575562',
        19 => '__anonymous__ad9b_1225379122',
        20 => '__anonymous__ad9b_353335263',
        21 => '__anonymous__ad9b_2021859385',
        22 => '__anonymous__ad9b_38224610',
        23 => '__anonymous__ad9b_1362371042',
      ),
    ),
  ),
  'contentTemplate' => 
  array (
    'class' => 'Arceau\\Template\\ContentTemplate',
    'external' => false,
    'weak' => false,
  ),
  'cotisationDao' => 
  array (
    'class' => 'Arceau\\Model\\DAOs\\CotisationDao',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'entityManager',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'customRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'custom',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbConnection' => 
  array (
    'class' => 'Mouf\\Database\\DBConnection\\MySqlConnection',
    'external' => false,
    'fieldProperties' => 
    array (
      'host' => 
      array (
        'value' => 'DB_HOST',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'port' => 
      array (
        'value' => 'DB_PORT',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'user' => 
      array (
        'value' => 'DB_USERNAME',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'password' => 
      array (
        'value' => 'DB_PASSWORD',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'dbname' => 
      array (
        'value' => 'DB_NAME',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalConnection' => 
  array (
    'class' => 'Doctrine\\DBAL\\Connection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return array(
			    "host" => DB_HOST,
			    "user" => DB_USERNAME,
			    "password" => DB_PASSWORD,
			    "port" => DB_PORT,
			    "dbname" => DB_NAME,
			    "charset" => "utf8",
			    "driverOptions" => array(
			        1002 =>"SET NAMES utf8"
			    )
			);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '__anonymous__ad9b_1662283823',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'doctrineConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => '__anonymous__ad9b_960329136',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalConnectionHelper' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Helper\\ConnectionHelper',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalImportCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\ImportCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbalReservedWordsCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\ReservedWordsCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbalRunSqlCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\RunSqlCommand',
    'external' => false,
    'weak' => false,
  ),
  'defaultDoctrineCache' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\Common\\Cache\\ArrayCache',
    'external' => false,
    'code' => '// If DEBUG mode is on, let\'s just use an ArrayCache.
if (DEBUG) {
	$driver = new \\Doctrine\\Common\\Cache\\ArrayCache();
} else {
	// If APC is available, let\'s use APC
	if (extension_loaded("apc")) {
		$driver = new \\Doctrine\\Common\\Cache\\ApcCache();
	} else {
		$driver = new \\Doctrine\\Common\\Cache\\FileCache(sys_get_temp_dir().\'/doctrinecache\');
	}
}
$driver->setNamespace(SECRET);
return $driver;
',
  ),
  'defaultLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'defaultMappingDriver' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver',
    'external' => false,
    'code' => 'return new Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver($container->get(\'annotationReader\'), [ROOT_PATH . "src/Arceau/Model/Entities/"]);',
  ),
  'defaultRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\AutoChainRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'rootUrlInlineWebLibrary',
        1 => 'messageServiceLibrary',
        2 => 'component.jquery',
        3 => 'materializecss',
        4 => 'styleCss',
        5 => 'javascript.ckeditor',
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultRenderer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
    ),
  ),
  'doctrineApcCache' => 
  array (
    'class' => 'Doctrine\\Common\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
  ),
  'doctrineConfiguration' => 
  array (
    'class' => 'Doctrine\\ORM\\Configuration',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setQuoteStrategy' => 'escapingQuoteStrategy',
      'setNamingStrategy' => 'underscoreNamingStrategy',
      'setQueryCacheImpl' => 'doctrineApcCache',
      'setMetadataCacheImpl' => 'doctrineApcCache',
      'setResultCacheImpl' => 'doctrineApcCache',
      'setMetadataDriverImpl' => 'mappingDriverChain',
    ),
    'setterProperties' => 
    array (
      'setProxyDir' => 
      array (
        'value' => 'return ROOT_PATH."src/Arceau/Model/Proxies/";',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      'setProxyNamespace' => 
      array (
        'value' => 'Arceau\\Model\\Proxies',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setAutoGenerateProxyClasses' => 
      array (
        'value' => 'DEBUG',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'setFilterSchemaAssetsExpression' => 
      array (
        'value' => '/^(?!patches$).*/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doctrineMoufCache' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Cache\\DoctrineCacheAdapter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultDoctrineCache',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'emailValidator' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\EmailValidator',
    'external' => false,
    'weak' => false,
  ),
  'entityManager' => 
  array (
    'class' => 'Mouf\\Doctrine\\ORM\\MoufResetableEntityManager',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '$dbalConnection = $container->get("dbalConnection");
$dbalConnection->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");
return $dbalConnection;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'doctrineConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => '__anonymous__ad9b_960329136',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'Mouf\\Doctrine\\ORM\\EntityManager',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setEntitiesNamespace' => 
      array (
        'value' => 'Arceau\\Model\\Entities',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setProxyNamespace' => 
      array (
        'value' => 'Arceau\\Model\\Proxies',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDaoNamespace' => 
      array (
        'value' => 'Arceau\\Model\\DAOs',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => 4,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'escapingQuoteStrategy' => 
  array (
    'class' => 'Mouf\\Doctrine\\ORM\\Mapping\\EscapingQuoteStrategy',
    'external' => false,
    'weak' => false,
  ),
  'exceptionRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'phpVarsCheckRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'httpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fineCommonTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.i18n.fine/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'footerTemplate' => 
  array (
    'class' => 'Arceau\\Template\\FooterTemplate',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setCopyright' => 
      array (
        'value' => '2015 - PREVOT Alexis',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'headerTemplate' => 
  array (
    'class' => 'Arceau\\Template\\HeaderTemplate',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setTitle' => 
      array (
        'value' => 'Arceau Gestion',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'helperSet' => 
  array (
    'class' => 'Mouf\\Console\\HelperSet',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          'db' => 'dbalConnectionHelper',
          'em' => 'ormConnectionHelper',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'httpErrorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'contentBlock' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => 'DEBUG',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'indexController' => 
  array (
    'class' => 'Arceau\\Controllers\\IndexController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'bodyTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'entityManager',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => 'userDao',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      6 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.ckeditor' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.ckeditor/ckeditor/ckeditor.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'login' => 
  array (
    'class' => 'Mouf\\Security\\Controllers\\SimpleLoginController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'userService' => 'userService',
      'simpleLoginView' => '__anonymous__61bc_1625135474',
      'messageService' => 'userMessageService',
      'contentBlock' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'badCredentialsLabel' => 
      array (
        'value' => 'Sorry, your login or password seem to be incorrect',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoutRedirectUrl' => 
      array (
        'value' => 'login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'defaultRedirectUrl' => 
      array (
        'value' => 'admin/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'ifLoggedRedirectUrl' => 
      array (
        'value' => 'admin/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mappingDriverChain' => 
  array (
    'class' => 'Mouf\\Doctrine\\ORM\\Mapping\\Driver\\MappingDriverChain',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setDefaultDriver' => 'defaultMappingDriver',
    ),
  ),
  'materializecss' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'node_modules/materialize-css/bin/materialize.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'node_modules/materialize-css/bin/materialize.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageServiceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.messageservice/messages.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageWidget' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Widget\\MessageWidget',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'messageProvider' => 'userMessageService',
    ),
  ),
  'moufTwigExtension' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigExtension',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'noCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\NoCache',
    'external' => false,
    'weak' => false,
  ),
  'notFoundRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'httpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'numericValidatorDecimals' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\NumericValidator',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'allowDecimals' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'ormConnectionHelper' => 
  array (
    'class' => 'Doctrine\\ORM\\Tools\\Console\\Helper\\EntityManagerHelper',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'entityManager',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.utils.weblibrarymanager' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.menu' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.menu/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.messageservice' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.messageservice/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/security.simplelogincontroller' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/security.simplelogincontroller/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patchService' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchService',
    'external' => false,
    'weak' => false,
  ),
  'phpVarsCheckRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'splashDefaultRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'psr.errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'warning',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rendererCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\InMemoryCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'chainWith' => 'apcCacheService',
    ),
  ),
  'requiredValidator' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\RequiredValidator',
    'external' => false,
    'weak' => false,
  ),
  'rightDao' => 
  array (
    'class' => 'Arceau\\Model\\DAOs\\RightDao',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'entityManager',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rightsService' => 
  array (
    'class' => 'Mouf\\Security\\RightsService\\MoufRightService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'userService' => 'userService',
      'rightsDao' => 'rightDao',
    ),
    'fieldProperties' => 
    array (
    ),
  ),
  'rootUrlInlineWebLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\InlineWebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rootUrlJsFile',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootUrlJsFile' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/javascript/rootUrl.php',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'sessionManager' => 
  array (
    'class' => 'Mouf\\Utils\\Session\\SessionManager\\DefaultSessionManager',
    'external' => false,
  ),
  'splash' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Splash',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'whoopsMiddleware',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'splashCacheApc' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fallback' => 'splashCacheFile',
    ),
  ),
  'splashCacheFile' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'cacheDirectory' => 
      array (
        'value' => 'splashCache/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashDefaultRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'notFoundRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'splashCacheApc',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/mvc.splash-common/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'styleCss' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'public/css/style.css',
          1 => 'http://fonts.googleapis.com/icon?family=Material+Icons',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'twigDebugExtension' => 
  array (
    'class' => 'Twig_Extension_Debug',
    'external' => false,
    'weak' => false,
  ),
  'twigEnvironment' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironment',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setExtensions' => 
      array (
        0 => 'moufTwigExtension',
        1 => 'twigDebugExtension',
      ),
    ),
    'setterProperties' => 
    array (
    ),
  ),
  'uRLValidatorFtpHttps' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\URLValidator',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'allowFtp' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'allowHttps' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'underscoreNamingStrategy' => 
  array (
    'class' => 'Doctrine\\ORM\\Mapping\\UnderscoreNamingStrategy',
    'external' => false,
    'weak' => false,
  ),
  'userDao' => 
  array (
    'class' => 'Arceau\\Model\\DAOs\\UserDao',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'entityManager',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userMessageService' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Service\\SessionMessageService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
    ),
  ),
  'userService' => 
  array (
    'class' => 'Mouf\\Security\\UserService\\UserService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
      'authenticationListeners' => 
      array (
        0 => 'rightsService',
      ),
      'userDao' => 'userDao',
      'log' => 'psr.errorLogLogger',
    ),
    'fieldProperties' => 
    array (
      'sessionPrefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'loginPageUrl' => 
      array (
        'value' => 'login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validatorsBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
  ),
  'validatorsTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.common.validators/src/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'validatorsBrowserLanguageDetection',
    ),
  ),
  'whoopsMiddleware' => 
  array (
    'class' => 'Whoops\\StackPhp\\WhoopsMiddleWare',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'exceptionRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));


unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class Mouf {
	public function getClosures() {
		return [
			'annotationReader' => function(ContainerInterface $container) {
				// Using composer autoloader
$loader = require ROOT_PATH . 'vendor/autoload.php';
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

// Creating a new AnnotationReader
$reader = new \Doctrine\Common\Annotations\AnnotationReader();
return new \Doctrine\Common\Annotations\CachedReader($reader, $container->get("defaultDoctrineCache"));
			},
			'dbalConnection' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return array(
			    "host" => DB_HOST,
			    "user" => DB_USERNAME,
			    "password" => DB_PASSWORD,
			    "port" => DB_PORT,
			    "dbname" => DB_NAME,
			    "charset" => "utf8",
			    "driverOptions" => array(
			        1002 =>"SET NAMES utf8"
			    )
			);
					},
				],
			],
			'defaultDoctrineCache' => function(ContainerInterface $container) {
				// If DEBUG mode is on, let's just use an ArrayCache.
if (DEBUG) {
	$driver = new \Doctrine\Common\Cache\ArrayCache();
} else {
	// If APC is available, let's use APC
	if (extension_loaded("apc")) {
		$driver = new \Doctrine\Common\Cache\ApcCache();
	} else {
		$driver = new \Doctrine\Common\Cache\FileCache(sys_get_temp_dir().'/doctrinecache');
	}
}
$driver->setNamespace(SECRET);
return $driver;

			},
			'defaultMappingDriver' => function(ContainerInterface $container) {
				return new Doctrine\ORM\Mapping\Driver\AnnotationDriver($container->get('annotationReader'), [ROOT_PATH . "src/Arceau/Model/Entities/"]);
			},
			'doctrineConfiguration' => [
				'setterProperties' => [
					'setProxyDir' => function(ContainerInterface $container) {
						return ROOT_PATH."src/Arceau/Model/Proxies/";
					},
				],
			],
			'entityManager' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						$dbalConnection = $container->get("dbalConnection");
$dbalConnection->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");
return $dbalConnection;
					},
				],
			],
			'moufTwigExtension' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
				],
			],
		];
	}
	/**
	 * @return Doctrine\Common\Annotations\CachedReader
	 */
	 public static function getAnnotationReader() {
	 	return MoufManager::getMoufManager()->get('annotationReader');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->get('apcCacheService');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->get('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->get('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->get('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->get('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->get('block.right');
	 }

	/**
	 * @return Arceau\Template\BodyTemplate
	 */
	 public static function getBodyTemplate() {
	 	return MoufManager::getMoufManager()->get('bodyTemplate');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getBootstrapRenderer() {
	 	return MoufManager::getMoufManager()->get('bootstrapRenderer');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getBootstrapTemplate() {
	 	return MoufManager::getMoufManager()->get('bootstrapTemplate');
	 }

	/**
	 * @return Arceau\Model\DAOs\ClientDao
	 */
	 public static function getClientDao() {
	 	return MoufManager::getMoufManager()->get('clientDao');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getComponent_bootstrap() {
	 	return MoufManager::getMoufManager()->get('component.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getComponent_jquery() {
	 	return MoufManager::getMoufManager()->get('component.jquery');
	 }

	/**
	 * @return Mouf\Console\ConsoleApplication
	 */
	 public static function getConsole() {
	 	return MoufManager::getMoufManager()->get('console');
	 }

	/**
	 * @return Arceau\Template\ContentTemplate
	 */
	 public static function getContentTemplate() {
	 	return MoufManager::getMoufManager()->get('contentTemplate');
	 }

	/**
	 * @return Arceau\Model\DAOs\CotisationDao
	 */
	 public static function getCotisationDao() {
	 	return MoufManager::getMoufManager()->get('cotisationDao');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getCustomRenderer() {
	 	return MoufManager::getMoufManager()->get('customRenderer');
	 }

	/**
	 * @return Mouf\Database\DBConnection\MySqlConnection
	 */
	 public static function getDbConnection() {
	 	return MoufManager::getMoufManager()->get('dbConnection');
	 }

	/**
	 * @return Doctrine\DBAL\Connection
	 */
	 public static function getDbalConnection() {
	 	return MoufManager::getMoufManager()->get('dbalConnection');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper
	 */
	 public static function getDbalConnectionHelper() {
	 	return MoufManager::getMoufManager()->get('dbalConnectionHelper');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\ImportCommand
	 */
	 public static function getDbalImportCommand() {
	 	return MoufManager::getMoufManager()->get('dbalImportCommand');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\ReservedWordsCommand
	 */
	 public static function getDbalReservedWordsCommand() {
	 	return MoufManager::getMoufManager()->get('dbalReservedWordsCommand');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\RunSqlCommand
	 */
	 public static function getDbalRunSqlCommand() {
	 	return MoufManager::getMoufManager()->get('dbalRunSqlCommand');
	 }

	/**
	 * @return Doctrine\Common\Cache\ArrayCache
	 */
	 public static function getDefaultDoctrineCache() {
	 	return MoufManager::getMoufManager()->get('defaultDoctrineCache');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getDefaultLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('defaultLanguageDetection');
	 }

	/**
	 * @return Doctrine\ORM\Mapping\Driver\AnnotationDriver
	 */
	 public static function getDefaultMappingDriver() {
	 	return MoufManager::getMoufManager()->get('defaultMappingDriver');
	 }

	/**
	 * @return Mouf\Html\Renderer\AutoChainRenderer
	 */
	 public static function getDefaultRenderer() {
	 	return MoufManager::getMoufManager()->get('defaultRenderer');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getDefaultTranslationService() {
	 	return MoufManager::getMoufManager()->get('defaultTranslationService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->get('defaultWebLibraryManager');
	 }

	/**
	 * @return Doctrine\Common\Cache\ApcCache
	 */
	 public static function getDoctrineApcCache() {
	 	return MoufManager::getMoufManager()->get('doctrineApcCache');
	 }

	/**
	 * @return Doctrine\ORM\Configuration
	 */
	 public static function getDoctrineConfiguration() {
	 	return MoufManager::getMoufManager()->get('doctrineConfiguration');
	 }

	/**
	 * @return Mouf\Utils\Common\Doctrine\Cache\DoctrineCacheAdapter
	 */
	 public static function getDoctrineMoufCache() {
	 	return MoufManager::getMoufManager()->get('doctrineMoufCache');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\EmailValidator
	 */
	 public static function getEmailValidator() {
	 	return MoufManager::getMoufManager()->get('emailValidator');
	 }

	/**
	 * @return Mouf\Doctrine\ORM\MoufResetableEntityManager
	 */
	 public static function getEntityManager() {
	 	return MoufManager::getMoufManager()->get('entityManager');
	 }

	/**
	 * @return Mouf\Utils\Log\ErrorLogLogger
	 */
	 public static function getErrorLogLogger() {
	 	return MoufManager::getMoufManager()->get('errorLogLogger');
	 }

	/**
	 * @return Mouf\Doctrine\ORM\Mapping\EscapingQuoteStrategy
	 */
	 public static function getEscapingQuoteStrategy() {
	 	return MoufManager::getMoufManager()->get('escapingQuoteStrategy');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\ExceptionRouter
	 */
	 public static function getExceptionRouter() {
	 	return MoufManager::getMoufManager()->get('exceptionRouter');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->get('fileCacheService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getFineCommonTranslationService() {
	 	return MoufManager::getMoufManager()->get('fineCommonTranslationService');
	 }

	/**
	 * @return Arceau\Template\FooterTemplate
	 */
	 public static function getFooterTemplate() {
	 	return MoufManager::getMoufManager()->get('footerTemplate');
	 }

	/**
	 * @return Arceau\Template\HeaderTemplate
	 */
	 public static function getHeaderTemplate() {
	 	return MoufManager::getMoufManager()->get('headerTemplate');
	 }

	/**
	 * @return Mouf\Console\HelperSet
	 */
	 public static function getHelperSet() {
	 	return MoufManager::getMoufManager()->get('helperSet');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getHttpErrorsController() {
	 	return MoufManager::getMoufManager()->get('httpErrorsController');
	 }

	/**
	 * @return Arceau\Controllers\IndexController
	 */
	 public static function getIndexController() {
	 	return MoufManager::getMoufManager()->get('indexController');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_ckeditor() {
	 	return MoufManager::getMoufManager()->get('javascript.ckeditor');
	 }

	/**
	 * @return Mouf\Security\Controllers\SimpleLoginController
	 */
	 public static function getLogin() {
	 	return MoufManager::getMoufManager()->get('login');
	 }

	/**
	 * @return Mouf\Doctrine\ORM\Mapping\Driver\MappingDriverChain
	 */
	 public static function getMappingDriverChain() {
	 	return MoufManager::getMoufManager()->get('mappingDriverChain');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMaterializecss() {
	 	return MoufManager::getMoufManager()->get('materializecss');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMessageServiceLibrary() {
	 	return MoufManager::getMoufManager()->get('messageServiceLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Widget\MessageWidget
	 */
	 public static function getMessageWidget() {
	 	return MoufManager::getMoufManager()->get('messageWidget');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigExtension
	 */
	 public static function getMoufTwigExtension() {
	 	return MoufManager::getMoufManager()->get('moufTwigExtension');
	 }

	/**
	 * @return Mouf\Utils\Cache\NoCache
	 */
	 public static function getNoCacheService() {
	 	return MoufManager::getMoufManager()->get('noCacheService');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\NotFoundRouter
	 */
	 public static function getNotFoundRouter() {
	 	return MoufManager::getMoufManager()->get('notFoundRouter');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\NumericValidator
	 */
	 public static function getNumericValidatorDecimals() {
	 	return MoufManager::getMoufManager()->get('numericValidatorDecimals');
	 }

	/**
	 * @return Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper
	 */
	 public static function getOrmConnectionHelper() {
	 	return MoufManager::getMoufManager()->get('ormConnectionHelper');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_utils_weblibrarymanager() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.utils.weblibrarymanager');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_menu() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.menu');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_messageservice() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.messageservice');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufsecurity_simplelogincontroller() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/security.simplelogincontroller');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchService
	 */
	 public static function getPatchService() {
	 	return MoufManager::getMoufManager()->get('patchService');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\PhpVarsCheckRouter
	 */
	 public static function getPhpVarsCheckRouter() {
	 	return MoufManager::getMoufManager()->get('phpVarsCheckRouter');
	 }

	/**
	 * @return Mouf\Utils\Log\Psr\ErrorLogLogger
	 */
	 public static function getPsr_errorLogLogger() {
	 	return MoufManager::getMoufManager()->get('psr.errorLogLogger');
	 }

	/**
	 * @return Mouf\Utils\Cache\InMemoryCache
	 */
	 public static function getRendererCacheService() {
	 	return MoufManager::getMoufManager()->get('rendererCacheService');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\RequiredValidator
	 */
	 public static function getRequiredValidator() {
	 	return MoufManager::getMoufManager()->get('requiredValidator');
	 }

	/**
	 * @return Arceau\Model\DAOs\RightDao
	 */
	 public static function getRightDao() {
	 	return MoufManager::getMoufManager()->get('rightDao');
	 }

	/**
	 * @return Mouf\Security\RightsService\MoufRightService
	 */
	 public static function getRightsService() {
	 	return MoufManager::getMoufManager()->get('rightsService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\InlineWebLibrary
	 */
	 public static function getRootUrlInlineWebLibrary() {
	 	return MoufManager::getMoufManager()->get('rootUrlInlineWebLibrary');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getRootUrlJsFile() {
	 	return MoufManager::getMoufManager()->get('rootUrlJsFile');
	 }

	/**
	 * @return Mouf\Utils\Session\SessionManager\DefaultSessionManager
	 */
	 public static function getSessionManager() {
	 	return MoufManager::getMoufManager()->get('sessionManager');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->get('splash');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('splashBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getSplashCacheApc() {
	 	return MoufManager::getMoufManager()->get('splashCacheApc');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getSplashCacheFile() {
	 	return MoufManager::getMoufManager()->get('splashCacheFile');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\SplashDefaultRouter
	 */
	 public static function getSplashDefaultRouter() {
	 	return MoufManager::getMoufManager()->get('splashDefaultRouter');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->get('splashTranslateService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getStyleCss() {
	 	return MoufManager::getMoufManager()->get('styleCss');
	 }

	/**
	 * @return Twig_Extension_Debug
	 */
	 public static function getTwigDebugExtension() {
	 	return MoufManager::getMoufManager()->get('twigDebugExtension');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigEnvironment
	 */
	 public static function getTwigEnvironment() {
	 	return MoufManager::getMoufManager()->get('twigEnvironment');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\URLValidator
	 */
	 public static function getURLValidatorFtpHttps() {
	 	return MoufManager::getMoufManager()->get('uRLValidatorFtpHttps');
	 }

	/**
	 * @return Doctrine\ORM\Mapping\UnderscoreNamingStrategy
	 */
	 public static function getUnderscoreNamingStrategy() {
	 	return MoufManager::getMoufManager()->get('underscoreNamingStrategy');
	 }

	/**
	 * @return Arceau\Model\DAOs\UserDao
	 */
	 public static function getUserDao() {
	 	return MoufManager::getMoufManager()->get('userDao');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Service\SessionMessageService
	 */
	 public static function getUserMessageService() {
	 	return MoufManager::getMoufManager()->get('userMessageService');
	 }

	/**
	 * @return Mouf\Security\UserService\UserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->get('userService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getValidatorsBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('validatorsBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getValidatorsTranslateService() {
	 	return MoufManager::getMoufManager()->get('validatorsTranslateService');
	 }

	/**
	 * @return Whoops\StackPhp\WhoopsMiddleWare
	 */
	 public static function getWhoopsMiddleware() {
	 	return MoufManager::getMoufManager()->get('whoopsMiddleware');
	 }

}
