<?php

/*
* This file has been automatically generated by Mouf/ORM.
* DO NOT edit this file, as it might be overwritten.
* If you need to perform changes, edit the RightDao class instead!
*/

namespace Arceau\Model\DAOs;

use Mouf\Database\DAOInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Arceau\Model\Entities\Right;

/**
 * The RightBaseDao class will maintain the persistance of Right class into the Rights table.


 */
class RightBaseDao extends EntityRepository implements DAOInterface
{
    /**
     * @param EntityManagerInterface $entityManager
     */
    public function __construct($entityManager)
    {
        parent::__construct($entityManager, $entityManager->getClassMetadata('Arceau\Model\Entities\Right'));
    }

    /**
     * Get a new bean record.
     *
     * @return Right the new bean object
     */
    public function create()
    {
        return new Right();
    }

    /**
     * Get a bean by it's Id.
     *
     * @param mixed $id
     *
     * @return Right the bean object
     */
    public function getById($id)
    {
        return $this->find($id);
    }

    /**
     * Peforms saving on a bean object.
     *
     * @param mixed bean object
     */
    public function save($entity)
    {
        $this->getEntityManager()->persist($entity);
    }

    /**
     * Peforms remove on a bean object.
     *
     * @param Right $entity the bean object
     */
    public function remove(Right $entity)
    {
        $this->getEntityManager()->remove($entity);
    }

    /**
     * Returns the lis of beans.
     *
     * @return Right[] array of bean objects
     */
    public function getList()
    {
        return $this->findAll();
    }

    /**
     * Finds only one entity. The criteria must contain all the elements needed to find a unique entity.
     * Throw an exception if more than one entity was found.
     *
     * @param array $criteria
     *
     * @return Right the bean object
     */
    public function findUniqueBy(array $criteria)
    {
        $result = $this->findBy($criteria);

        if (count($result) == 1) {
            return $result[0];
        } elseif (count($result) > 1) {
            throw new NonUniqueResultException('More than one Right was found');
        } else {
            return;
        }
    }

}
